development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: 'do-not-reply@example.com'
  :password: '[my password]'
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: xxx
  :password: yyy
  :enable_starttls_auto: true
